DELETE http://localhost:8000/api/blogs/660331f498a7119fc1cb58e4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkF0b20iLCJpZCI6IjY2MDMxOGNhMmE5N2FiYTc2NmRhYmY3YiIsImlhdCI6MTcxMTU1NDU3Mn0.HIqpInEb2cXh-DPSnJ1WmZfHMvlqqMqfM3O3n1ADb6w